version: 2
updates:
  # Keep NuGet packages up to date
  - package-ecosystem: "nuget"
    directory: "/"                # scans all .csproj/.sln under repo
    schedule:
      interval: "weekly"          # daily | weekly | monthly
    open-pull-requests-limit: 5
    target-branch: "main"

  # Keep GitHub Actions versions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
