name: User Story
description: Create a user story for ProgressionLab
title: "story: "
labels: ["story"]
body:
  - type: markdown
    attributes:
      value: |
        Write user stories in the format:
        **As a** <user>, **I want** <goal>, **so that** <benefit>.
  - type: textarea
    id: story
    attributes:
      label: Story
      placeholder: "As a lifter, I want automatic next-week targets, so that I don’t have to update Excel mid-workout."
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Bullet points that define success. Each bullet is testable.
      placeholder: |
        - When I complete a session, the system computes next week's targets using the rule engine
        - Rounds to the nearest 2.5 lb (or 1.25 kg) increment
        - Caps at RPE 9; auto-deload if RPE ≥ 9.5
      render: markdown
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Out of scope (for clarity)
      placeholder: "Not implementing Apple Watch UI in this story"
      render: markdown
  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      options:
        - label: Tests updated/added (unit/integration)
        - label: Docs updated (README / /docs)
        - label: Logging & errors handled
        - label: Feature behind a flag if incomplete
  - type: textarea
    id: notes
    attributes:
      label: Notes / Links
      placeholder: "Design doc, ADR, reference links"
      render: markdown
